<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_todos_new-todo</name>
   <tag></tag>
   <elementGuidId>9b023ad3-903e-44fa-a084-0b94c8e9da1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.new-todo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34abc463-1e36-4ac6-b7a1-172b243ade46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-todo</value>
      <webElementGuid>3c3c37a6-651b-460a-b46a-8df06eb5e1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What needs to be done?</value>
      <webElementGuid>8d6ae259-e1ba-4417-80cf-e03bf12e04ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.1</value>
      <webElementGuid>8216cc09-e654-4599-abaf-ac359908c3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;learn-bar&quot;]/section[@class=&quot;todoapp&quot;]/div[1]/header[@class=&quot;header&quot;]/input[@class=&quot;new-todo&quot;]</value>
      <webElementGuid>ff1c698b-b00e-41d2-8149-851270548ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>6e2bb52e-7683-4a68-896e-82d8e289cb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bc3f1457-35b1-4a18-8615-d07f890abe51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'What needs to be done?']</value>
      <webElementGuid>1a030acb-a80b-4d44-928f-8ec565899fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
